export const COMPLETED_MODULES = "COMPLETED_MODULES";
export const COMPLETED_SECTION = "COMPLETED_SECTION ";
export const COMPLETED_LESSON = "COMPLETED_LESSON";
export const COMPLETED_PARAGRAPH = "COMPLETED_PARAGRAPH";



